classdef jointstatesMsg < robotics.ros.Message
    %jointstatesMsg MATLAB implementation of vehicle_control/jointstatesMsg
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'vehicle_control/jointstatesMsg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '5adcb9804213862ca45087cb776e92ad' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Fl
        Fr
        Bl
        Br
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Bl', 'Br', 'Fl', 'Fr'} % List of non-constant message properties
        ROSPropertyList = {'bl', 'br', 'fl', 'fr'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = jointstatesMsg(msg)
            %jointstatesMsg Construct the message object jointstatesMsg
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function fl = get.Fl(obj)
            %get.Fl Get the value for property Fl
            fl = double(obj.JavaMessage.getFl);
        end
        
        function set.Fl(obj, fl)
            %set.Fl Set the value for property Fl
            validateattributes(fl, {'numeric'}, {'nonempty', 'scalar'}, 'jointstatesMsg', 'Fl');
            
            obj.JavaMessage.setFl(fl);
        end
        
        function fr = get.Fr(obj)
            %get.Fr Get the value for property Fr
            fr = double(obj.JavaMessage.getFr);
        end
        
        function set.Fr(obj, fr)
            %set.Fr Set the value for property Fr
            validateattributes(fr, {'numeric'}, {'nonempty', 'scalar'}, 'jointstatesMsg', 'Fr');
            
            obj.JavaMessage.setFr(fr);
        end
        
        function bl = get.Bl(obj)
            %get.Bl Get the value for property Bl
            bl = double(obj.JavaMessage.getBl);
        end
        
        function set.Bl(obj, bl)
            %set.Bl Set the value for property Bl
            validateattributes(bl, {'numeric'}, {'nonempty', 'scalar'}, 'jointstatesMsg', 'Bl');
            
            obj.JavaMessage.setBl(bl);
        end
        
        function br = get.Br(obj)
            %get.Br Get the value for property Br
            br = double(obj.JavaMessage.getBr);
        end
        
        function set.Br(obj, br)
            %set.Br Set the value for property Br
            validateattributes(br, {'numeric'}, {'nonempty', 'scalar'}, 'jointstatesMsg', 'Br');
            
            obj.JavaMessage.setBr(br);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Fl = obj.Fl;
            cpObj.Fr = obj.Fr;
            cpObj.Bl = obj.Bl;
            cpObj.Br = obj.Br;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Fl = strObj.Fl;
            obj.Fr = strObj.Fr;
            obj.Bl = strObj.Bl;
            obj.Br = strObj.Br;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Fl = obj.Fl;
            strObj.Fr = obj.Fr;
            strObj.Bl = obj.Bl;
            strObj.Br = obj.Br;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.vehicle_control.jointstatesMsg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.vehicle_control.jointstatesMsg;
            obj.reload(strObj);
        end
    end
end
