classdef positionMsg < robotics.ros.Message
    %positionMsg MATLAB implementation of vehicle_control/positionMsg
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'vehicle_control/positionMsg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e84defd7a9fcbc40d44267fa83d59eae' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        X
        Y
        Qx
        Qy
        Qz
        Qw
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Qw', 'Qx', 'Qy', 'Qz', 'X', 'Y'} % List of non-constant message properties
        ROSPropertyList = {'qw', 'qx', 'qy', 'qz', 'x', 'y'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = positionMsg(msg)
            %positionMsg Construct the message object positionMsg
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function x = get.X(obj)
            %get.X Get the value for property X
            x = double(obj.JavaMessage.getX);
        end
        
        function set.X(obj, x)
            %set.X Set the value for property X
            validateattributes(x, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'X');
            
            obj.JavaMessage.setX(x);
        end
        
        function y = get.Y(obj)
            %get.Y Get the value for property Y
            y = double(obj.JavaMessage.getY);
        end
        
        function set.Y(obj, y)
            %set.Y Set the value for property Y
            validateattributes(y, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'Y');
            
            obj.JavaMessage.setY(y);
        end
        
        function qx = get.Qx(obj)
            %get.Qx Get the value for property Qx
            qx = double(obj.JavaMessage.getQx);
        end
        
        function set.Qx(obj, qx)
            %set.Qx Set the value for property Qx
            validateattributes(qx, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'Qx');
            
            obj.JavaMessage.setQx(qx);
        end
        
        function qy = get.Qy(obj)
            %get.Qy Get the value for property Qy
            qy = double(obj.JavaMessage.getQy);
        end
        
        function set.Qy(obj, qy)
            %set.Qy Set the value for property Qy
            validateattributes(qy, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'Qy');
            
            obj.JavaMessage.setQy(qy);
        end
        
        function qz = get.Qz(obj)
            %get.Qz Get the value for property Qz
            qz = double(obj.JavaMessage.getQz);
        end
        
        function set.Qz(obj, qz)
            %set.Qz Set the value for property Qz
            validateattributes(qz, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'Qz');
            
            obj.JavaMessage.setQz(qz);
        end
        
        function qw = get.Qw(obj)
            %get.Qw Get the value for property Qw
            qw = double(obj.JavaMessage.getQw);
        end
        
        function set.Qw(obj, qw)
            %set.Qw Set the value for property Qw
            validateattributes(qw, {'numeric'}, {'nonempty', 'scalar'}, 'positionMsg', 'Qw');
            
            obj.JavaMessage.setQw(qw);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.X = obj.X;
            cpObj.Y = obj.Y;
            cpObj.Qx = obj.Qx;
            cpObj.Qy = obj.Qy;
            cpObj.Qz = obj.Qz;
            cpObj.Qw = obj.Qw;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.X = strObj.X;
            obj.Y = strObj.Y;
            obj.Qx = strObj.Qx;
            obj.Qy = strObj.Qy;
            obj.Qz = strObj.Qz;
            obj.Qw = strObj.Qw;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.X = obj.X;
            strObj.Y = obj.Y;
            strObj.Qx = obj.Qx;
            strObj.Qy = obj.Qy;
            strObj.Qz = obj.Qz;
            strObj.Qw = obj.Qw;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.vehicle_control.positionMsg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.vehicle_control.positionMsg;
            obj.reload(strObj);
        end
    end
end
