classdef realVel < robotics.ros.Message
    %realVel MATLAB implementation of epos_tutorial/realVel
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'epos_tutorial/realVel' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '260e0cec7f1efbe2a3d504ab70436964' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        RealVel
    end
    
    properties (Constant, Hidden)
        PropertyList = {'RealVel'} % List of non-constant message properties
        ROSPropertyList = {'realVel'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = realVel(msg)
            %realVel Construct the message object realVel
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function realvel = get.RealVel(obj)
            %get.RealVel Get the value for property RealVel
            javaArray = obj.JavaMessage.getRealVel;
            array = obj.readJavaArray(javaArray, 'int32');
            realvel = int32(array);
        end
        
        function set.RealVel(obj, realvel)
            %set.RealVel Set the value for property RealVel
            validateattributes(realvel, {'numeric'}, {'vector', 'numel', 4}, 'realVel', 'RealVel');
            
            javaArray = obj.JavaMessage.getRealVel;
            array = obj.writeJavaArray(realvel, javaArray, 'int32');
            obj.JavaMessage.setRealVel(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.RealVel = obj.RealVel;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.RealVel = strObj.RealVel;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RealVel = obj.RealVel;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.epos_tutorial.realVel.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.epos_tutorial.realVel;
            obj.reload(strObj);
        end
    end
end
